// __next/components/Layout.tsx
import React from 'react';
import Head from 'next/head';
import Header from '@/components/Header';
import Footer from './Footer';
import { Alert } from '@/components/Alert';
import { SkipLink } from '@/components/SkipLink/SkipLink';

type LayoutProps = {
  preview?: boolean;
  pageProps?: any;
  children?: React.ReactNode;
};

export const Layout = ({ preview = false, pageProps, children }: LayoutProps): JSX.Element => {
  return (
    <>
      <Head>
        <meta name="viewport" content="initial-scale=1, viewport-fit=cover" />
      </Head>

      <SkipLink />

      <Header />
      <Alert preview={preview} />

      <main id="main" role="main">
        {children}
      </main>

      <Footer />
    </>
  );
};

// src/routes/__layout.svelte
<script lang='ts'>
import '../styles/fonts.css';
import '../styles/app.scss';
import Header from '../components/Header.svelte';
import Footer from '../components/Footer.svelte';
import SkipLink from '../components/SkipLink.svelte';
import Alert from '../components/Alert.svelte';
</script>

<svelte:head>
  <meta name="viewport" content="initial-scale=1, viewport-fit=cover" />
</svelte:head>

<SkipLink />
<Header/>

<!--TODO: fix here, should be preview=preview-->
<Alert preview={false}/>

<main id='main' role='main'>
  <slot></slot>
</main>

<Footer/>
