// pages/writings/index.tsx
import React from 'react';
import { getSiteData, getAllPosts, getAllMenu } from '@/lib/api';
import PostAbstract from '@/components/PostAbstract';
import { generateRSS } from '@/lib/rss-utils';
import { useRouter } from 'next/router';

export default function Writings({ page }) {
  const router = useRouter();

  return (
    <section key={router.route} className="posts">
      <h1>Writings</h1>

      <div>
        {
          page && page.map(post => <PostAbstract key={post.id} post={post} />)
          // <!--      <div class="posts__pagination">-->
          //   <!--        <a href="#">Older entries</a>-->
          //   <!--        <a href="#">Newer entries</a>-->
          //   <!--      </div>-->
        }
      </div>

      {!page && (
        <div>
          <p className="sorry">Nothing new here, please come back later...</p>
        </div>
      )}
    </section>
  );
}

export async function getStaticProps({ preview = false }) {
  const page = (await getAllPosts(preview)) || null;
  const menu = (await getAllMenu(preview)) || null;
  const site = (await getSiteData(preview)) || null;

  await generateRSS(page);

  return {
    props: {
      site,
      page,
      menu
    }
  };
}

// pages/writings/index.vue
<template>
  <section class="posts">
    <h1>Writings</h1>

    <div v-if="allPosts && allPosts.length > 0">
      <PostAbstract v-for="post in allPosts" :key="post.id" :post="post"></PostAbstract>

      <!--      <div class="posts__pagination">-->
      <!--        <a href="#">Older entries</a>-->
      <!--        <a href="#">Newer entries</a>-->
      <!--      </div>-->
    </div>

    <div v-else>
      <p class="sorry">Nothing new here, please come back later...</p>
    </div>
  </section>
</template>

<script>
import { mapState } from 'vuex';
import PostAbstract from '../../components/PostAbstract';

export default {
  name: 'Writings',

  components: { PostAbstract },

  // head() {
  //   return {
  //     // title: this.$t('home.title'),
  //     // titleTemplate: null,
  //     meta: [
  //       ...this.getSeoMetaData()
  //     ]
  //   };
  // },

  computed: {
    // mix this into the outer object with the object spread operator
    ...mapState({
      allPosts: state => state.writings
    })
  },

  //
  // methods: {
  //   getSeoMetaData: function () {
  //     if (!this.home) {
  //       return [];
  //     }
  //
  //     return this.home.seoMetaTags.filter(meta => meta.tag === 'meta')
  //       .map((meta) => {
  //         if (meta.attributes !== null) {
  //
  //           const m = {};
  //           const attributes = Object.keys(meta.attributes);
  //
  //           for (let index = 0; index < attributes.length; index++) {
  //             m[attributes[index]] = meta.attributes[attributes[index]];
  //             m.hid = attributes[index];
  //           }
  //
  //           return m;
  //         }
  //       });
  //   }
  // }
};
</script>
