// components/PostAbstract.vue
<template>
  <article :aria-labelledby="`aria-post-${post.id}`"
           class="post post--abstract"
           itemscope
           itemtype="http://http://schema.org/BlogPosting"
           role="article"
  >
    <header>
      <h2 :id="`aria-post-${post.id}`" itemprop="name">
        <nuxt-link :to="`writings/${post.slug}`" exact rel="bookmark">{{ post.title }}</nuxt-link>
      </h2>

      <div class="post__metadata">
        <span class="visuallyhidden">Posted </span>
        <p v-if="post.category">
          <em class="visuallyhidden">in </em>
          <span>{{ post.category }}</span>
        </p>
        <p v-else></p>

        <p>
          <span class="visuallyhidden"> on </span>
          <time itemprop="datePublished" :datetime="getPublishedDateShort">{{ getPublishedDateFormatted }}</time>
        </p>
      </div>
    </header>

    <div v-html="getAbstract"></div>
  </article>
</template>

<script>
import { format } from 'date-fns';
import stripHtml from 'string-strip-html';

export default {
  name: 'PostAbstract',

  props: {
    post: {
      required: true,
      type: Object,
      default: () => {
        return undefined;
      }
    }
  },

  computed: {
    getPublishedDateFormatted() {
      return format(
        new Date(this.post._publishedAt),
        'MMMM do yyyy'
      );
    },

    getPublishedDateShort() {
      return format(
        new Date(this.post._publishedAt),
        'yyyy-MM-dd'
      );
    },

    getAbstract() {
      const text = stripHtml(this.post.body);

      if (text.length >= 200) {
        return `${text.substr(0, 200)}...`;
      }

      return text;
    }
  }
};
</script>

// components/PostAbstract.tsx
import React from 'react';
import Link from 'next/link';
import { getPublishedDateFormatted, getPublishedDateShort } from '@/lib/helpers';
import { Post } from '@/types/index';

export type PostAbstractProps = {
  post: Post;
};

const PostAbstract = ({ post }: PostAbstractProps): JSX.Element => (
  <article
    aria-labelledby={`aria-article-${post.id}`}
    className="post"
    itemScope
    itemType="http://http://schema.org/BlogPosting"
  >
    <header>
      <h2 id={`aria-article-${post.id}`} itemProp="name">
        <Link href={`/writings/${post.slug}`}>
          <a>{post.title}</a>
        </Link>
      </h2>

      <div className="post__metadata">
        <span>Posted in &nbsp;</span>

        {post.category && (
          <p>
            <span>{post.category}</span>
          </p>
        )}
        <span>&nbsp; on &nbsp;</span>
        <p>
          <time itemProp="datePublished" dateTime={getPublishedDateShort(post.publishedAt)}>
            {getPublishedDateFormatted(post.publishedAt)}
          </time>
        </p>
      </div>
    </header>
  </article>
);

export default PostAbstract;
