// src/components/What.svelte
<script lang="ts">

import type { Home } from "../types";

export let home: Home;
</script>

<article id="whatido" class="whatido">
  <h2>{home.whatidoHeading}</h2>

  <section class="whatido__items">
    {#each home.whatido as item}
      <div class="whatido__item">
        <div class="WhatidoItemContainer">
          <div class="WhatidoItemContent">
            <p class="whatido__title">
              <span>{item.title}</span>
            </p>
            <p class="whatido__description">
              <span>{item.description}</span>
            </p>
          </div>

          <figure role="presentation" class="Figure">
            {#if item.cover}
              <div class="ImageWrapper">
                <picture>
                  <source
                    srcset={item.cover.responsiveImage.webpSrcSet}
                    sizes={item.cover.responsiveImage.sizes}
                    type="image/webp"
                  />
                  <source srcset={item.cover.responsiveImage.srcSet} sizes={item.cover.responsiveImage.sizes} />
                  <img alt="" src={item.cover.responsiveImage.src} />
                </picture>
              </div>
            {/if}
          </figure>
        </div>
      </div>
    {/each}
  </section>
</article>

<style lang="scss">
  @import '../styles/shared';

  .whatido {
    --whatido-item-title-line-height-min: 1.5em; // use 'em' otherwise the fluid-type mixin doesn't work
    --whatido-item-title-line-height-max: 1.5em;
    --whatido-item-title-font-size-min: 2rem;
    --whatido-item-title-font-size-max: 3.45rem;

    //@include container;
    margin-bottom: 5rem;
    padding-top: calc(3 * var(--text-base-size));

    h2 {
      width: 100%;
      max-width: none;
      @include container;
      padding: 0 1rem;
    }

    ul {
      list-style-type: none;
      display: grid;
      grid-template-columns: repeat(6, 1fr);
      grid-template-rows: auto;
      gap: 1rem;
      width: 100%;
      max-width: none;
      margin: 0;
      padding: 0 1rem;
      overflow: hidden;
    }

    li {
      width: 100%;
      grid-column: 1/6;
      margin-bottom: 3rem;
      overflow: hidden;
    }

  }

  .whatido__items {

  }

  .whatido__title {
    --color-text: var(--color-black);
    position: relative;
    width: 100%;
    margin: 0 auto 1rem auto;
    max-width: 570px;
    padding: 0 0 1rem 0;

    color: var(--color-text);
    --text-weight: 700;
    font-family: var(--heading-font-family);

    font-size: clamp(var(--whatido-item-title-font-size-min), 11vw, var(--whatido-item-title-font-size-max));
    line-height: var(--whatido-item-title-line-height-min);
    text-transform: capitalize;
    z-index: 2;
  }

  .whatido__description {
    --color-text: var(--color-black);
    position: relative;
    width: 100%;
    max-width: 570px;
    margin: 0;
    padding: 0 1rem 0 0;
    color: var(--color-text);
    z-index: 1;
    transition: clip-path 1.5s ease;
  }

  .whatido__title span,
  .whatido__description span {
    display: block;
  }

  .whatido__item {
    &:nth-child(even) {
      background-color: var(--color-black);

      .whatido__title {
        --color-text: var(--color-white);
      }

      .whatido__description {
        --color-text: var(--color-white);
      }
    }
  }

  .WhatidoItemContainer {
    position: relative;
    display: grid;
    grid-template-columns: 1fr 1fr;

    width: 100%;
    margin: 0 auto;
    padding: 0 0 0 3rem;

    @media (max-width: 42em) {
      grid-template-columns: 1fr;
      padding: 0;
    }

    //@include media("<tablet") {
    //  padding: 0 0 0 1.5rem;
    //}

    @media (min-width: 64em) and (max-width: 1092px) {
      padding: 0 0 0 1.5rem;
    }

    @media (min-width: 72em) {
      padding: 0;
    }

  }

  .WhatidoItemContent {
    grid-column: 1/2;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    height: 100vh;
    z-index: 2;

    p {
      overflow: hidden;
    }

    @media (max-width: 42em) {
      padding: 0 0 0 1.5rem;
    }
  }

  .whatido__item {

    &:nth-child(even) {
      .whatido__item-content {
        background-color: rgba(0, 0, 0, .8);
      }
    }

    &:nth-child(odd) {
      .whatido__item-content {
        background-color: rgba(255, 255, 255, .8);
      }
    }
  }


  .Figure {
    overflow: hidden;
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    //opacity: 0.5;

    @media (min-width: 42em) {
      grid-column: 2/3;
      position: relative;
      opacity: 1;
    }
  }

  .ImageWrapper {
    position: absolute;
    left: 0;
    top: 50%;
    transform: translateY(-50%);
    width: 100%;
    height: 160vh;
    overflow: hidden;

    img,
    picture {
      object-fit: cover;
      width: 100%;
      height: 100%;
    }
  }
</style>

// components/What.tsx
import React, { useRef, Fragment } from 'react';
import { WhatidoData } from '@/types/index';

const What = ({ heading, items }: WhatidoData): JSX.Element => {
  const itemsRef = useRef();
  // const isClient = typeof window !== 'undefined';

  return (
    <article id="whatido" className="whatido">
      <h2>{heading}</h2>

      <section ref={itemsRef} className="whatido__items">
        {items &&
          items.map(item => (
            <Fragment key={item.title}>
              <div className="whatido__item">
                <div className="whatido__item-container">
                  <div className="whatido__item-content">
                    <p className="whatido__title">
                      <span>{item.title}</span>
                    </p>
                    <p className="whatido__description">
                      <span>{item.description}</span>
                    </p>
                  </div>
                  <figure role="presentation">
                    {item.cover && (
                      <div className="image-wrapper">
                        <picture>
                          <source
                            srcSet={item.cover.responsiveImage.webpSrcSet}
                            sizes={item.cover.responsiveImage.sizes}
                            type="image/webp"
                          />
                          <source srcSet={item.cover.responsiveImage.srcSet} sizes={item.cover.responsiveImage.sizes} />
                          {/* eslint-disable-next-line @next/next/no-img-element */}
                          <img alt="" src={item.cover.responsiveImage.src} />
                        </picture>
                      </div>
                    )}
                  </figure>
                </div>
              </div>
            </Fragment>
          ))}
      </section>
    </article>
  );
};

export default What;
